// Tipos de datos:
//  - Number
//  - String
//  - Boolean
//  - Null
//  - Undefined
//  - Object
//  - Symbol
//  - Function
//  - Array
//  - Date
//  - RegExp
//  - Error
//  - Map
//  - Set
//  - WeakMap
//  - WeakSet
//  - Promise
//  - Iterator
//  - Generator
//  - GeneratorFunction
//  - AsyncFunction
//  - AsyncGenerator
//  - AsyncGeneratorFunction
//  - GeneratorObject
//  - AsyncGeneratorObject
//  - Proxy
//  - Reflect
//  - Int8Array
//  - Uint8Array
//  - Uint8ClampedArray
//  - Int16Array
//  - Uint16Array
//  - Int32Array
//  - Uint32Array
//  - Float32Array
//  - Float64Array
//  - BigInt64Array
//  - BigUint64Array
//  - DataView
//  - ArrayBuffer
//  - SharedArrayBuffer
//  - Atomics
//  - JSON
//  - MapIterator
//  - SetIterator
//  - StringIterator
//  - ArrayIterator
//  - Int8ArrayIterator


